from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Callable

from langchain_core.tools import BaseTool

from capability_system.tools.contracts import (
    ToolPromptExposurePolicy,
    ToolExecutionContract,
    ToolOutputContract,
    ToolProjectionContract,
    ToolResolutionContract,
    ToolResourceExposurePolicy,
    ToolRuntimeVisibility,
)
from permissions.operation_packages import default_tool_packages
from permissions.operations import build_default_operation_registry
from capability_system.tools.tool_units.agent_todo_tool import AgentTodoTool
from capability_system.tools.tool_units.browser_control_tool import BrowserControlTool
from capability_system.tools.tool_units.fetch_url_tool import FetchURLTool
from capability_system.tools.tool_units.file_system_tools import GlobPathsTool, ListDirTool, PathExistsTool, StatPathTool
from capability_system.tools.tool_units.git_tools import (
    GitBranchCreateTool,
    GitBranchListTool,
    GitCommitTool,
    GitDiffTool,
    GitLogTool,
    GitPushTool,
    GitRestoreTool,
    GitShowTool,
    GitStageTool,
    GitStatusTool,
    GitUnstageTool,
)
from capability_system.tools.tool_units.image_generation_tool import ImageGenerationTool
from capability_system.tools.tool_units.memory_search_tool import MemorySearchTool
from capability_system.tools.tool_units.python_repl_tool import PythonReplTool
from capability_system.tools.tool_units.python_ast_tools import PythonCodeOutlineTool, PythonParseCheckTool, PythonSymbolSearchTool
from capability_system.tools.tool_units.read_file_tool import ReadFileTool
from capability_system.tools.tool_units.search_files_tool import SearchFilesTool, SearchTextTool
from capability_system.tools.tool_units.structured_file_tool import ReadStructuredFileTool
from capability_system.tools.tool_units.subagent_control_tool import (
    CloseSubagentTool,
    ListSubagentsTool,
    SendSubagentMessageTool,
    SpawnSubagentTool,
    WaitSubagentTool,
)
from capability_system.tools.tool_units.terminal_tool import TerminalTool
from capability_system.tools.tool_units.text_metric_tool import TextMetricTool
from capability_system.tools.tool_units.web_search_tool import WebSearchTool
from capability_system.tools.tool_units.write_file_tool import EditFileTool, WriteFileTool


ToolFactory = Callable[[Path], BaseTool]
_OPERATION_REGISTRY = build_default_operation_registry()


@dataclass(frozen=True, slots=True)
class ToolDefinition:
    name: str
    display_name: str
    operation_id: str
    module: str
    factory: ToolFactory
    contract: ToolExecutionContract = field(default_factory=ToolExecutionContract)
    resolution_contract: ToolResolutionContract = field(default_factory=ToolResolutionContract)
    output_contract: ToolOutputContract = field(default_factory=ToolOutputContract)
    projection_contract: ToolProjectionContract = field(default_factory=ToolProjectionContract)
    capability_tags: list[str] = field(default_factory=list)
    supported_modalities: list[str] = field(default_factory=list)
    safety_tags: list[str] = field(default_factory=list)
    route_hints: list[str] = field(default_factory=list)
    safe_for_auto_route: bool = False
    schema_identity: str = ""
    runtime_visibility: ToolRuntimeVisibility = "main_runtime"
    prompt_exposure_policy: ToolPromptExposurePolicy = "schema_only"
    resource_exposure_policy: ToolResourceExposurePolicy = "none"
    is_read_only: bool = field(init=False)
    is_destructive: bool = field(init=False)
    is_concurrency_safe: bool = field(init=False)

    def __post_init__(self) -> None:
        operation = _OPERATION_REGISTRY.get_operation(self.operation_id)
        if operation is None:
            raise ValueError(f"Tool {self.name!r} references unknown operation {self.operation_id!r}")
        object.__setattr__(self, "is_read_only", bool(operation.read_only))
        object.__setattr__(self, "is_destructive", bool(operation.destructive))
        object.__setattr__(self, "is_concurrency_safe", bool(operation.concurrency_safe))

    def build(self, base_dir: Path) -> BaseTool:
        return self.factory(base_dir)

    def to_registry_record(self) -> dict[str, Any]:
        payload = asdict(self)
        payload.pop("factory", None)
        return payload


def _tool_definitions() -> list[ToolDefinition]:
    return [
        ToolDefinition(
            name="agent_todo",
            display_name="Agent Todo",
            operation_id="op.agent_todo",
            module="tools.agent_todo_tool",
            factory=lambda base_dir: AgentTodoTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                optional_inputs=["operation", "session_id", "task_id", "items", "todo_id", "status", "notes"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["todo", "planning", "progress_tracking", "agent_state"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["state", "non_destructive"],
            route_hints=["tool", "agent_todo", "task_progress"],
            safe_for_auto_route=False,
            schema_identity="local.tools/agent_todo",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="spawn_subagent",
            display_name="启动子 Agent",
            operation_id="op.subagent_spawn",
            module="tools.subagent_control_tool",
            factory=lambda base_dir: SpawnSubagentTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["target_agent_id", "goal"],
                optional_inputs=["instructions", "context_refs", "expected_outputs"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["agent", "subagent", "lifecycle"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["agent_execution", "state"],
            route_hints=["tool", "subagent", "spawn"],
            safe_for_auto_route=False,
            schema_identity="local.tools/spawn_subagent",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="send_subagent_message",
            display_name="发送子 Agent 消息",
            operation_id="op.subagent_message",
            module="tools.subagent_control_tool",
            factory=lambda base_dir: SendSubagentMessageTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["subagent_run_ref", "message"],
                optional_inputs=["context_refs"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["agent", "subagent", "lifecycle"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["agent_execution", "state"],
            route_hints=["tool", "subagent", "message"],
            safe_for_auto_route=False,
            schema_identity="local.tools/send_subagent_message",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="wait_subagent",
            display_name="等待子 Agent",
            operation_id="op.subagent_wait",
            module="tools.subagent_control_tool",
            factory=lambda base_dir: WaitSubagentTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["subagent_run_ref"],
                optional_inputs=["since_message_ref"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["agent", "subagent", "lifecycle"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["agent_execution", "state"],
            route_hints=["tool", "subagent", "wait"],
            safe_for_auto_route=False,
            schema_identity="local.tools/wait_subagent",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="list_subagents",
            display_name="列出子 Agent",
            operation_id="op.subagent_list",
            module="tools.subagent_control_tool",
            factory=lambda base_dir: ListSubagentsTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                optional_inputs=["status"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["agent", "subagent", "lifecycle"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["agent_execution", "state"],
            route_hints=["tool", "subagent", "list"],
            safe_for_auto_route=False,
            schema_identity="local.tools/list_subagents",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="close_subagent",
            display_name="关闭子 Agent",
            operation_id="op.subagent_close",
            module="tools.subagent_control_tool",
            factory=lambda base_dir: CloseSubagentTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["subagent_run_ref"],
                optional_inputs=["reason"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["agent", "subagent", "lifecycle"],
            supported_modalities=["task", "workspace", "text"],
            safety_tags=["agent_execution", "state"],
            route_hints=["tool", "subagent", "close"],
            safe_for_auto_route=False,
            schema_identity="local.tools/close_subagent",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="web_search",
            display_name="网页搜索",
            operation_id="op.web_search",
            module="tools.web_search_tool",
            factory=lambda base_dir: WebSearchTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["search", "news", "finance", "official-docs"],
            supported_modalities=["web", "realtime"],
            safety_tags=["read", "network"],
            route_hints=["tool", "latest_information"],
            safe_for_auto_route=True,
            schema_identity="local.tools/web_search",
        ),
        ToolDefinition(
            name="list_dir",
            display_name="列出目录",
            operation_id="op.list_dir",
            module="tools.file_system_tools",
            factory=lambda base_dir: ListDirTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "directory", "workspace", "path"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "directory_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/list_dir",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="stat_path",
            display_name="查看路径信息",
            operation_id="op.stat_path",
            module="tools.file_system_tools",
            factory=lambda base_dir: StatPathTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "metadata"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "path_metadata"],
            safe_for_auto_route=False,
            schema_identity="local.tools/stat_path",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="path_exists",
            display_name="检查路径是否存在",
            operation_id="op.path_exists",
            module="tools.file_system_tools",
            factory=lambda base_dir: PathExistsTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "existence"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "path_check"],
            safe_for_auto_route=False,
            schema_identity="local.tools/path_exists",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="glob_paths",
            display_name="按通配符查找路径",
            operation_id="op.glob_paths",
            module="tools.file_system_tools",
            factory=lambda base_dir: GlobPathsTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["pattern"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "glob"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_path_search", "glob_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/glob_paths",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="search_files",
            display_name="搜索文件",
            operation_id="op.search_files",
            module="tools.search_files_tool",
            factory=lambda base_dir: SearchFilesTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "search", "path", "workspace", "workspace_path_search"],
            supported_modalities=["text", "code", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_path_search", "file_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/search_files",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="search_text",
            display_name="搜索文本",
            operation_id="op.search_text",
            module="tools.search_files_tool",
            factory=lambda base_dir: SearchTextTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "search", "text_search", "workspace", "code_search"],
            supported_modalities=["text", "code", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_text_search", "text_search", "code_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/search_text",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="read_file",
            display_name="读取文件",
            operation_id="op.read_file",
            module="tools.read_file_tool",
            factory=lambda base_dir: ReadFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(
                path_field="path",
                path_kind="workspace",
            ),
            output_contract=ToolOutputContract(display_mode="verbatim_text"),
            capability_tags=["file", "read", "local"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/read_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="read_structured_file",
            display_name="读取结构化文件",
            operation_id="op.read_structured_file",
            module="tools.structured_file_tool",
            factory=lambda base_dir: ReadStructuredFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "read", "structured_config", "workspace"],
            supported_modalities=["text", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "structured_config"],
            safe_for_auto_route=False,
            schema_identity="local.tools/read_structured_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="python_code_outline",
            display_name="Python 代码结构",
            operation_id="op.python_code_outline",
            module="tools.python_ast_tools",
            factory=lambda base_dir: PythonCodeOutlineTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                optional_inputs=["max_symbols"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["python", "ast", "code_outline", "symbol_index", "code_intelligence"],
            supported_modalities=["code", "workspace"],
            safety_tags=["read", "official_ast"],
            route_hints=["tool", "python_code", "code_outline", "symbol_index"],
            safe_for_auto_route=True,
            schema_identity="local.tools/python_code_outline",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="python_parse_check",
            display_name="Python 语法检查",
            operation_id="op.python_parse_check",
            module="tools.python_ast_tools",
            factory=lambda base_dir: PythonParseCheckTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["python", "ast", "parse_check", "diagnostics", "code_intelligence"],
            supported_modalities=["code", "workspace"],
            safety_tags=["read", "official_ast"],
            route_hints=["tool", "python_code", "parse_check", "diagnostics"],
            safe_for_auto_route=True,
            schema_identity="local.tools/python_parse_check",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="python_symbol_search",
            display_name="Python 符号搜索",
            operation_id="op.python_symbol_search",
            module="tools.python_ast_tools",
            factory=lambda base_dir: PythonSymbolSearchTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                optional_inputs=["roots", "max_results"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["python", "ast", "symbol_search", "code_intelligence", "workspace"],
            supported_modalities=["code", "workspace"],
            safety_tags=["read", "official_ast"],
            route_hints=["tool", "python_code", "symbol_search", "code_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/python_symbol_search",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="memory_search",
            display_name="搜索任务记忆",
            operation_id="op.memory_read",
            module="tools.memory_search_tool",
            factory=lambda base_dir: MemorySearchTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                optional_inputs=["task_run_id", "project_id", "repositories", "collections", "limit"],
                owner_scope="task_memory",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["memory", "search", "formal_memory", "task_memory"],
            supported_modalities=["text", "memory"],
            safety_tags=["read", "memory_read"],
            route_hints=["tool", "memory_read", "task_memory_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/memory_search",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="text_metric",
            display_name="文本计量",
            operation_id="op.text_metric",
            module="tools.text_metric_tool",
            factory=lambda base_dir: TextMetricTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                optional_inputs=["text", "path", "measurement_mode"],
                owner_scope="explicit_text_or_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["text", "metric", "length_budget", "word_count", "content_quality"],
            supported_modalities=["text", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "text_metric", "word_count", "length_budget"],
            safe_for_auto_route=True,
            schema_identity="local.tools/text_metric",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="fetch_url",
            display_name="抓取网页",
            operation_id="op.fetch_url",
            module="tools.fetch_url_tool",
            factory=lambda _base_dir: FetchURLTool(),
            contract=ToolExecutionContract(
                required_inputs=["url"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["web", "fetch", "verification"],
            supported_modalities=["web"],
            safety_tags=["read", "network"],
            route_hints=["tool", "verification"],
            safe_for_auto_route=False,
            schema_identity="local.tools/fetch_url",
        ),
        ToolDefinition(
            name="browser_control",
            display_name="网页操作",
            operation_id="op.browser_control",
            module="tools.browser_control_tool",
            factory=lambda base_dir: BrowserControlTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["action"],
                optional_inputs=["url", "selector", "text", "value", "timeout_ms", "screenshot_name"],
                owner_scope="browser_session",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["browser", "web", "automation", "page_interaction", "visual_verification"],
            supported_modalities=["web", "browser", "visual"],
            safety_tags=["network", "interactive", "external_write_possible"],
            route_hints=["tool", "browser", "web_automation", "page_operation"],
            safe_for_auto_route=False,
            schema_identity="local.tools/browser_control",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="image_generate",
            display_name="生成图像",
            operation_id="op.image_generate",
            module="tools.image_generation_tool",
            factory=lambda base_dir: ImageGenerationTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["prompt"],
                optional_inputs=["target_id", "asset_kind", "size", "output_size", "overwrite"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_canonical"),
            capability_tags=["image", "image_generation", "visual", "creative", "multimodal"],
            supported_modalities=["image", "visual"],
            safety_tags=["write", "external_model"],
            route_hints=["tool", "image_generation", "generate_image", "visual_creation"],
            safe_for_auto_route=True,
            schema_identity="local.tools/image_generate",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_status",
            display_name="查看 Git 状态",
            operation_id="op.git_status",
            module="tools.git_tools",
            factory=lambda base_dir: GitStatusTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "status", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_status",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_diff",
            display_name="查看 Git 差异",
            operation_id="op.git_diff",
            module="tools.git_tools",
            factory=lambda base_dir: GitDiffTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "diff", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_diff",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_log",
            display_name="查看 Git 日志",
            operation_id="op.git_log",
            module="tools.git_tools",
            factory=lambda base_dir: GitLogTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "log", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_log",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_show",
            display_name="查看 Git 对象",
            operation_id="op.git_show",
            module="tools.git_tools",
            factory=lambda base_dir: GitShowTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "show", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_show",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_branch_list",
            display_name="查看 Git 分支",
            operation_id="op.git_branch_list",
            module="tools.git_tools",
            factory=lambda base_dir: GitBranchListTool(root_dir=base_dir),
            contract=ToolExecutionContract(optional_inputs=["all_branches"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "branch", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_branch_list",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_branch_create",
            display_name="创建 Git 分支",
            operation_id="op.git_branch_create",
            module="tools.git_tools",
            factory=lambda base_dir: GitBranchCreateTool(root_dir=base_dir),
            contract=ToolExecutionContract(required_inputs=["branch_name"], optional_inputs=["start_point"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "branch", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write"],
            route_hints=["tool", "git_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_branch_create",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_stage",
            display_name="暂存 Git 文件",
            operation_id="op.git_stage",
            module="tools.git_tools",
            factory=lambda base_dir: GitStageTool(root_dir=base_dir),
            contract=ToolExecutionContract(required_inputs=["paths"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "stage", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write"],
            route_hints=["tool", "git_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_stage",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_unstage",
            display_name="取消暂存 Git 文件",
            operation_id="op.git_unstage",
            module="tools.git_tools",
            factory=lambda base_dir: GitUnstageTool(root_dir=base_dir),
            contract=ToolExecutionContract(required_inputs=["paths"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "unstage", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write"],
            route_hints=["tool", "git_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_unstage",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_commit",
            display_name="提交 Git 版本",
            operation_id="op.git_commit",
            module="tools.git_tools",
            factory=lambda base_dir: GitCommitTool(root_dir=base_dir),
            contract=ToolExecutionContract(required_inputs=["message"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "commit", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write"],
            route_hints=["tool", "git_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_commit",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_restore",
            display_name="恢复 Git 文件",
            operation_id="op.git_restore",
            module="tools.git_tools",
            factory=lambda base_dir: GitRestoreTool(root_dir=base_dir),
            contract=ToolExecutionContract(required_inputs=["paths"], optional_inputs=["staged"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "restore", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write", "destructive"],
            route_hints=["tool", "git_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_restore",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="git_push",
            display_name="推送 Git 分支",
            operation_id="op.git_push",
            module="tools.git_tools",
            factory=lambda base_dir: GitPushTool(root_dir=base_dir),
            contract=ToolExecutionContract(optional_inputs=["remote", "branch"], owner_scope="none", context_policy="inline", result_channel="canonical"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "push", "remote", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["write", "git_write", "network", "remote"],
            route_hints=["tool", "git_remote"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_push",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="write_file",
            display_name="写入文件",
            operation_id="op.write_file",
            module="tools.write_file_tool",
            factory=lambda base_dir: WriteFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path", "content"],
                owner_scope="explicit_path",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_if_canonical"),
            capability_tags=["file", "write", "workspace"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["write", "local_write"],
            route_hints=["tool", "workspace_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/write_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="edit_file",
            display_name="编辑文件",
            operation_id="op.edit_file",
            module="tools.write_file_tool",
            factory=lambda base_dir: EditFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path", "old_text", "new_text"],
                owner_scope="explicit_path",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_if_canonical"),
            capability_tags=["file", "edit", "workspace"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["write", "local_write"],
            route_hints=["tool", "workspace_edit"],
            safe_for_auto_route=False,
            schema_identity="local.tools/edit_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
        ),
        ToolDefinition(
            name="terminal",
            display_name="终端命令",
            operation_id="op.shell",
            module="tools.terminal_tool",
            factory=lambda base_dir: TerminalTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["command"],
                owner_scope="none",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="tool_raw",
            ),
            output_contract=ToolOutputContract(display_mode="raw_debug_only", persistence_policy="do_not_persist"),
            capability_tags=["shell", "terminal", "command"],
            supported_modalities=["system"],
            safety_tags=["write", "shell", "destructive"],
            route_hints=["tool", "local_command"],
            safe_for_auto_route=False,
            schema_identity="local.tools/terminal",
            runtime_visibility="main_runtime",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
        ),
        ToolDefinition(
            name="python_repl",
            display_name="Python 执行",
            operation_id="op.python_repl",
            module="tools.python_repl_tool",
            factory=lambda base_dir: PythonReplTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["code"],
                owner_scope="none",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="tool_raw",
            ),
            output_contract=ToolOutputContract(display_mode="raw_debug_only", persistence_policy="do_not_persist"),
            capability_tags=["python", "repl", "scripting"],
            supported_modalities=["system"],
            safety_tags=["write", "compute", "shell"],
            route_hints=["tool", "local_scripting"],
            safe_for_auto_route=False,
            schema_identity="local.tools/python_repl",
            runtime_visibility="agent_internal",
            prompt_exposure_policy="hidden",
            resource_exposure_policy="none",
        ),
    ]


def get_tool_definitions() -> list[ToolDefinition]:
    return list(_tool_definitions())


def get_tool_definition_map() -> dict[str, ToolDefinition]:
    return {definition.name: definition for definition in get_tool_definitions()}


def build_tool_instances(base_dir: Path) -> list[BaseTool]:
    return [definition.build(base_dir) for definition in get_tool_definitions()]


def build_tool_registry_payload() -> dict[str, Any]:
    definitions = get_tool_definitions()
    operation_ids_in_packages = {
        operation_id
        for package in default_tool_packages()
        for operation_id in package.operation_ids
    }
    return {
        "version": 2,
        "tool_count": len(definitions),
        "tools": [definition.to_registry_record() for definition in definitions],
        "tool_packages": [package.to_dict() for package in default_tool_packages()],
        "default_library": [
            {
                "tool_name": definition.name,
                "operation_id": definition.operation_id,
            }
            for definition in definitions
            if definition.operation_id not in operation_ids_in_packages
        ],
    }


