from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass(frozen=True, slots=True)
class OperationDescriptor:
    operation_id: str
    operation_type: str
    title: str
    capability_summary: str
    provider: str = "builtin"
    aliases: tuple[str, ...] = ()
    input_contract: dict[str, Any] = field(default_factory=dict)
    output_contract: dict[str, Any] = field(default_factory=dict)
    input_contract_ref: str = ""
    output_contract_ref: str = ""
    risk_tags: tuple[str, ...] = ()
    read_only: bool = False
    destructive: bool = False
    idempotent: bool = False
    open_world: bool = False
    concurrency_safe: bool = False
    requires_user_interaction: bool = False
    requires_approval_by_default: bool = False
    max_result_size_chars: int = 0
    interrupt_behavior: str = "defer"
    deferred_loading: bool = False
    always_load: bool = False
    safety_validator_ref: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class OperationRegistry:
    def __init__(self, operations: list[OperationDescriptor] | None = None) -> None:
        self._operations: dict[str, OperationDescriptor] = {}
        self._aliases: dict[str, str] = {}
        for operation in operations or []:
            self.register(operation)

    def register(self, operation: OperationDescriptor) -> None:
        self._operations[operation.operation_id] = operation
        self._aliases[operation.operation_id] = operation.operation_id
        for alias in operation.aliases:
            if alias:
                self._aliases[alias] = operation.operation_id

    def normalize_id(self, operation_id: str) -> str:
        value = str(operation_id or "").strip()
        return self._aliases.get(value, value)

    def get_operation(self, operation_id: str) -> OperationDescriptor | None:
        return self._operations.get(self.normalize_id(operation_id))

    def list_operations(self) -> list[OperationDescriptor]:
        return [self._operations[key] for key in sorted(self._operations)]

    def export_manifest(self) -> dict[str, Any]:
        return {
            "authority": "operation_registry",
            "operations": [operation.to_dict() for operation in self.list_operations()],
        }


def _descriptor(
    operation_id: str,
    operation_type: str,
    title: str,
    capability_summary: str,
    *,
    aliases: tuple[str, ...] = (),
    risk_tags: tuple[str, ...] = (),
    read_only: bool = False,
    destructive: bool = False,
    idempotent: bool = False,
    open_world: bool = False,
    concurrency_safe: bool = False,
    requires_user_interaction: bool = False,
    requires_approval_by_default: bool = False,
    max_result_size_chars: int = 0,
    interrupt_behavior: str = "defer",
    deferred_loading: bool = False,
    always_load: bool = False,
    safety_validator_ref: str = "",
    metadata: dict[str, Any] | None = None,
) -> OperationDescriptor:
    input_contract_ref = f"{operation_id}.input"
    output_contract_ref = f"{operation_id}.output"
    return OperationDescriptor(
        operation_id=operation_id,
        operation_type=operation_type,
        title=title,
        capability_summary=capability_summary,
        aliases=aliases,
        input_contract={"contract_ref": input_contract_ref},
        output_contract={"contract_ref": output_contract_ref},
        input_contract_ref=input_contract_ref,
        output_contract_ref=output_contract_ref,
        risk_tags=risk_tags,
        read_only=read_only,
        destructive=destructive,
        idempotent=idempotent,
        open_world=open_world,
        concurrency_safe=concurrency_safe,
        requires_user_interaction=requires_user_interaction,
        requires_approval_by_default=requires_approval_by_default,
        max_result_size_chars=max_result_size_chars,
        interrupt_behavior=interrupt_behavior,
        deferred_loading=deferred_loading,
        always_load=always_load,
        safety_validator_ref=safety_validator_ref,
        metadata=dict(metadata or {}),
    )


def default_operation_descriptors() -> list[OperationDescriptor]:
    return [
        _descriptor(
            "op.model_response",
            "model",
            "Model response",
            "Generate the model response for the current agent invocation.",
            aliases=("model_response", "main_response"),
            risk_tags=("model_response", "read_only"),
            read_only=True,
            idempotent=False,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            interrupt_behavior="abort_safe",
            always_load=True,
        ),
        _descriptor(
            "op.agent_todo",
            "state",
            "Agent todo",
            "Maintain the current task's visible execution todo state.",
            aliases=("agent_todo",),
            risk_tags=("agent_state", "session_write_candidate", "non_destructive"),
            read_only=False,
            idempotent=False,
            concurrency_safe=False,
            max_result_size_chars=40_000,
            interrupt_behavior="checkpoint_then_abort",
        ),
        _descriptor(
            "op.subagent_spawn",
            "session",
            "Spawn subagent",
            "Create a real child agent run under the current task.",
            aliases=("spawn_subagent",),
            risk_tags=("agent_execution", "subagent_lifecycle", "state_write"),
            read_only=False,
            idempotent=False,
            concurrency_safe=False,
            interrupt_behavior="checkpoint_then_abort",
            deferred_loading=True,
        ),
        _descriptor(
            "op.subagent_message",
            "session",
            "Send subagent message",
            "Send a message to an existing child agent run.",
            aliases=("send_subagent_message",),
            risk_tags=("agent_execution", "subagent_lifecycle", "state_write"),
            read_only=False,
            idempotent=False,
            concurrency_safe=False,
            interrupt_behavior="checkpoint_then_abort",
            deferred_loading=True,
        ),
        _descriptor(
            "op.subagent_wait",
            "session",
            "Wait subagent",
            "Read a child agent mailbox once without blocking the main loop.",
            aliases=("wait_subagent",),
            risk_tags=("agent_execution", "subagent_lifecycle", "read_only"),
            read_only=True,
            idempotent=True,
            concurrency_safe=False,
            interrupt_behavior="abort_safe",
            deferred_loading=True,
        ),
        _descriptor(
            "op.subagent_list",
            "session",
            "List subagents",
            "List child agent runs for the current task and parent agent.",
            aliases=("list_subagents",),
            risk_tags=("agent_execution", "subagent_lifecycle", "read_only"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            interrupt_behavior="abort_safe",
            deferred_loading=True,
        ),
        _descriptor(
            "op.subagent_close",
            "session",
            "Close subagent",
            "Close or kill a child agent run owned by the current parent agent.",
            aliases=("close_subagent",),
            risk_tags=("agent_execution", "subagent_lifecycle", "state_write"),
            read_only=False,
            idempotent=False,
            concurrency_safe=False,
            interrupt_behavior="checkpoint_then_abort",
            deferred_loading=True,
        ),
        _descriptor(
            "op.read_file",
            "filesystem",
            "Read file",
            "Read task-relevant local workspace files.",
            aliases=("read_file",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.search_files",
            "filesystem",
            "Search files",
            "Find files in the local workspace.",
            aliases=("search_files",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.search_text",
            "filesystem",
            "Search text",
            "Search text in local workspace files.",
            aliases=("search_text",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.codebase_search",
            "agent_capability",
            "Codebase search capability",
            "Run the delegated read-only codebase search capability for a codebase search agent.",
            aliases=("codebase_search", "workspace_search", "local_search", "file_search"),
            risk_tags=("read_only", "local_read", "agent_capability", "codebase_search"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            safety_validator_ref="filesystem_path",
            metadata={
                "agent_id": "agent:codebase_searcher",
                "delegation_only": True,
                "required_operations": ["op.search_files", "op.search_text", "op.read_file"],
            },
        ),
        _descriptor(
            "op.list_dir",
            "filesystem",
            "List directory",
            "List entries in a known local workspace directory.",
            aliases=("list_dir",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.stat_path",
            "filesystem",
            "Stat path",
            "Return metadata for a local workspace path.",
            aliases=("stat_path",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=20_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.path_exists",
            "filesystem",
            "Path exists",
            "Check whether a local workspace path exists.",
            aliases=("path_exists",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=5_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.glob_paths",
            "filesystem",
            "Glob paths",
            "Find local workspace paths by explicit glob pattern.",
            aliases=("glob_paths",),
            risk_tags=("read_only", "local_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.read_structured_file",
            "filesystem",
            "Read structured file",
            "Parse a local JSON, YAML, or TOML configuration file.",
            aliases=("read_structured_file",),
            risk_tags=("read_only", "local_read", "structured_config"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.python_code_outline",
            "code_intelligence",
            "Python code outline",
            "Use Python's official ast standard library to summarize symbols in a local Python file.",
            aliases=("python_code_outline", "code_outline", "python_outline"),
            risk_tags=("read_only", "local_read", "python_ast", "code_intelligence"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.python_parse_check",
            "code_intelligence",
            "Python parse check",
            "Use Python's official ast standard library to check whether a local Python file parses successfully.",
            aliases=("python_parse_check", "parse_check", "python_ast_check"),
            risk_tags=("read_only", "local_read", "python_ast", "code_intelligence"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=20_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.python_symbol_search",
            "code_intelligence",
            "Python symbol search",
            "Use Python's official ast standard library to search Python symbols across local workspace files.",
            aliases=("python_symbol_search", "symbol_search", "python_symbols"),
            risk_tags=("read_only", "local_read", "python_ast", "code_intelligence"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.text_metric",
            "analysis",
            "Text metric",
            "Measure text length for task contracts using CJK characters plus Latin words, with explicit token-mode fallback diagnostics.",
            aliases=("text_metric", "word_count"),
            risk_tags=("read_only", "text_metric", "length_budget"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=20_000,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.web_search",
            "network",
            "Web search",
            "Search external web sources for current information.",
            aliases=("web_search",),
            risk_tags=("read_only", "network_open_world"),
            read_only=True,
            idempotent=True,
            open_world=True,
            concurrency_safe=True,
            max_result_size_chars=80_000,
            deferred_loading=True,
        ),
        _descriptor(
            "op.search_agent",
            "agent_capability",
            "DeepSearch capability",
            "Run the delegated multi-source DeepSearch capability for a search specialist agent.",
            aliases=("search_agent", "deepsearch"),
            risk_tags=("read_only", "agent_capability", "deepsearch"),
            read_only=True,
            idempotent=False,
            open_world=True,
            concurrency_safe=False,
            max_result_size_chars=120_000,
            deferred_loading=True,
            metadata={
                "agent_id": "agent:web_researcher",
                "delegation_only": True,
                "required_operations": ["op.web_search", "op.fetch_url"],
            },
        ),
        _descriptor(
            "op.fetch_url",
            "network",
            "Fetch URL",
            "Fetch a specific external URL for evidence gathering.",
            aliases=("fetch_url",),
            risk_tags=("read_only", "external_fetch"),
            read_only=True,
            idempotent=True,
            open_world=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            deferred_loading=True,
        ),
        _descriptor(
            "op.browser_control",
            "browser",
            "Browser control",
            "Operate a local browser page for web navigation, form input, page inspection, screenshots, and extraction.",
            aliases=("browser_control", "browser", "web_automation"),
            risk_tags=("network_open_world", "interactive_browser", "external_write_possible"),
            read_only=False,
            destructive=False,
            idempotent=False,
            open_world=True,
            concurrency_safe=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            max_result_size_chars=40_000,
            interrupt_behavior="defer",
            deferred_loading=True,
        ),
        _descriptor(
            "op.image_generate",
            "multimodal",
            "Image generation",
            "Generate a saved image asset from a precise visual prompt.",
            aliases=("image_generate", "generate_image", "text_to_image"),
            risk_tags=("external_model", "image_generation", "asset_write"),
            read_only=False,
            destructive=False,
            idempotent=False,
            open_world=False,
            concurrency_safe=False,
            max_result_size_chars=20_000,
            deferred_loading=True,
        ),
        _descriptor(
            "op.git_status",
            "vcs",
            "Git status",
            "Show read-only git working tree status.",
            aliases=("git_status",),
            risk_tags=("read_only", "git_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_diff",
            "vcs",
            "Git diff",
            "Show read-only git diff.",
            aliases=("git_diff",),
            risk_tags=("read_only", "git_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
        ),
        _descriptor(
            "op.git_log",
            "vcs",
            "Git log",
            "Show read-only git commit log.",
            aliases=("git_log",),
            risk_tags=("read_only", "git_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_show",
            "vcs",
            "Git show",
            "Show read-only git object or commit details.",
            aliases=("git_show",),
            risk_tags=("read_only", "git_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
        ),
        _descriptor(
            "op.git_branch_list",
            "vcs",
            "Git branch list",
            "List read-only git branches.",
            aliases=("git_branch_list",),
            risk_tags=("read_only", "git_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_branch_create",
            "vcs",
            "Git branch create",
            "Create a git branch without switching to it.",
            aliases=("git_branch_create",),
            risk_tags=("git_write", "local_write"),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_stage",
            "vcs",
            "Git stage",
            "Stage explicit workspace-relative paths.",
            aliases=("git_stage",),
            risk_tags=("git_write", "local_write"),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_unstage",
            "vcs",
            "Git unstage",
            "Remove explicit workspace-relative paths from the git index.",
            aliases=("git_unstage",),
            risk_tags=("git_write", "local_write"),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_commit",
            "vcs",
            "Git commit",
            "Commit staged git changes.",
            aliases=("git_commit",),
            risk_tags=("git_write", "local_write"),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_restore",
            "vcs",
            "Git restore",
            "Restore explicit workspace-relative paths from git.",
            aliases=("git_restore",),
            risk_tags=("git_write", "local_write", "destructive"),
            destructive=True,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.git_push",
            "vcs",
            "Git push",
            "Push a branch to a git remote without force.",
            aliases=("git_push",),
            risk_tags=("git_write", "remote_write", "network"),
            destructive=False,
            open_world=True,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            concurrency_safe=False,
            max_result_size_chars=40_000,
        ),
        _descriptor(
            "op.write_file",
            "filesystem",
            "Write file",
            "Create or overwrite a local file.",
            aliases=("write_file",),
            risk_tags=("local_write",),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.edit_file",
            "filesystem",
            "Edit file",
            "Modify an existing local file.",
            aliases=("edit_file",),
            risk_tags=("local_write",),
            destructive=False,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.shell",
            "shell",
            "Shell",
            "Run a local shell command.",
            aliases=("shell", "terminal", "op.terminal"),
            risk_tags=("shell_execution",),
            destructive=True,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            interrupt_behavior="terminate_process",
            safety_validator_ref="shell_read_only",
        ),
        _descriptor(
            "op.python_repl",
            "shell",
            "Python REPL",
            "Run local Python code.",
            aliases=("python_repl",),
            risk_tags=("python_execution",),
            destructive=True,
            requires_user_interaction=True,
            requires_approval_by_default=True,
            interrupt_behavior="terminate_process",
        ),
        _descriptor(
            "op.memory_read",
            "memory",
            "Memory read",
            "Read and search scoped formal task memory summaries.",
            aliases=("memory_read", "memory_search"),
            risk_tags=("read_only", "memory_read"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=40_000,
            metadata={"model_visible_tools": ["memory_search"], "database_search": True},
        ),
        _descriptor(
            "op.memory_write_candidate",
            "memory",
            "Memory write candidate",
            "Submit a memory write candidate for CommitGate review.",
            aliases=("memory_write_candidate",),
            risk_tags=("memory_write_candidate",),
            requires_approval_by_default=True,
            requires_user_interaction=True,
        ),
        _descriptor(
            "op.mcp_retrieval",
            "mcp",
            "Retrieval MCP",
            "Run a bounded retrieval MCP capability.",
            aliases=("mcp_retrieval",),
            risk_tags=("mcp_execution", "read_only"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            deferred_loading=True,
        ),
        _descriptor(
            "op.mcp_pdf",
            "mcp",
            "PDF MCP",
            "Run a bounded PDF analysis MCP capability.",
            aliases=("mcp_pdf",),
            risk_tags=("mcp_execution", "read_only", "local_read", "document_analysis"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            deferred_loading=True,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.mcp_structured_data",
            "mcp",
            "Structured data MCP",
            "Run a bounded structured-data MCP capability.",
            aliases=("mcp_structured_data",),
            risk_tags=("mcp_execution", "read_only", "local_read", "structured_data"),
            read_only=True,
            idempotent=True,
            concurrency_safe=True,
            max_result_size_chars=120_000,
            deferred_loading=True,
            safety_validator_ref="filesystem_path",
        ),
        _descriptor(
            "op.agent_bounded",
            "agent",
            "Bounded agent",
            "Run an isolated bounded specialist agent.",
            aliases=("agent_bounded",),
            risk_tags=("agent_execution",),
            requires_user_interaction=True,
            interrupt_behavior="checkpoint_then_abort",
            deferred_loading=True,
        ),
        _descriptor(
            "op.session_message_candidate",
            "session",
            "Session message candidate",
            "Submit a session message candidate for CommitGate.",
            aliases=("session_message_candidate",),
            risk_tags=("session_write_candidate",),
        ),
        _descriptor(
            "op.artifact_result_ref",
            "artifact",
            "Artifact result ref",
            "Submit an artifact result reference candidate.",
            aliases=("artifact_result_ref",),
            risk_tags=("artifact_write_candidate",),
        ),
    ]


def build_default_operation_registry() -> OperationRegistry:
    return OperationRegistry(default_operation_descriptors())


