from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Callable

from langchain_core.tools import BaseTool

from capability_system.tool_contracts import (
    ToolPromptExposurePolicy,
    ToolExecutionContract,
    ToolOutputContract,
    ToolProjectionContract,
    ToolResolutionContract,
    ToolResourceExposurePolicy,
    ToolRuntimeVisibility,
)
from capability_system.units.tools.analyze_multimodal_file_tool import AnalyzeMultimodalFileTool
from capability_system.units.tools.delegate_to_agent_tool import DelegateToAgentTool
from capability_system.units.tools.fetch_url_tool import FetchURLTool
from capability_system.units.tools.file_system_tools import GlobPathsTool, ListDirTool, PathExistsTool, StatPathTool
from capability_system.units.tools.git_tools import GitDiffTool, GitLogTool, GitShowTool, GitStatusTool
from capability_system.units.tools.index_multimodal_file_tool import IndexMultimodalFileTool
from capability_system.units.tools.python_repl_tool import PythonReplTool
from capability_system.units.tools.read_file_tool import ReadFileTool
from capability_system.units.tools.search_files_tool import SearchFilesTool, SearchTextTool
from capability_system.units.tools.structured_file_tool import ReadStructuredFileTool
from capability_system.units.tools.terminal_tool import TerminalTool
from capability_system.units.tools.web_search_tool import WebSearchTool
from capability_system.units.tools.write_file_tool import EditFileTool, WriteFileTool


ToolFactory = Callable[[Path], BaseTool]


@dataclass(frozen=True, slots=True)
class ToolDefinition:
    name: str
    display_name: str
    operation_id: str
    module: str
    factory: ToolFactory
    contract: ToolExecutionContract = field(default_factory=ToolExecutionContract)
    resolution_contract: ToolResolutionContract = field(default_factory=ToolResolutionContract)
    output_contract: ToolOutputContract = field(default_factory=ToolOutputContract)
    projection_contract: ToolProjectionContract = field(default_factory=ToolProjectionContract)
    capability_tags: list[str] = field(default_factory=list)
    supported_modalities: list[str] = field(default_factory=list)
    safety_tags: list[str] = field(default_factory=list)
    route_hints: list[str] = field(default_factory=list)
    safe_for_auto_route: bool = True
    schema_identity: str = ""
    runtime_visibility: ToolRuntimeVisibility = "main_runtime"
    prompt_exposure_policy: ToolPromptExposurePolicy = "schema_only"
    resource_exposure_policy: ToolResourceExposurePolicy = "none"
    is_read_only: bool = True
    is_destructive: bool = False
    is_concurrency_safe: bool = False

    def build(self, base_dir: Path) -> BaseTool:
        return self.factory(base_dir)

    def to_registry_record(self) -> dict[str, Any]:
        payload = asdict(self)
        payload.pop("factory", None)
        return payload


def _tool_definitions() -> list[ToolDefinition]:
    return [
        ToolDefinition(
            name="web_search",
            display_name="网页搜索",
            operation_id="op.web_search",
            module="tools.web_search_tool",
            factory=lambda base_dir: WebSearchTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["search", "news", "finance", "official-docs"],
            supported_modalities=["web", "realtime"],
            safety_tags=["read", "network"],
            route_hints=["tool", "latest_information"],
            safe_for_auto_route=True,
            schema_identity="local.tools/web_search",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="analyze_multimodal_file",
            display_name="多模态文件分析",
            operation_id="op.analyze_multimodal_file",
            module="tools.analyze_multimodal_file_tool",
            factory=lambda base_dir: AnalyzeMultimodalFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="isolated",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(
                path_field="path",
                path_kind="multimodal",
            ),
            output_contract=ToolOutputContract(display_mode="artifact_only"),
            capability_tags=["multimodal", "inspection", "preview"],
            supported_modalities=["pdf", "table", "image", "document"],
            safety_tags=["read", "compute"],
            route_hints=["tool", "file_preview"],
            safe_for_auto_route=False,
            schema_identity="local.tools/analyze_multimodal_file",
            runtime_visibility="agent_internal",
            prompt_exposure_policy="hidden",
            resource_exposure_policy="handle_only",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="index_multimodal_file",
            display_name="多模态文件索引",
            operation_id="op.index_multimodal_file",
            module="tools.index_multimodal_file_tool",
            factory=lambda base_dir: IndexMultimodalFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="artifact_only",
            ),
            resolution_contract=ToolResolutionContract(
                path_field="path",
                path_kind="multimodal",
            ),
            output_contract=ToolOutputContract(display_mode="artifact_only", persistence_policy="do_not_persist"),
            capability_tags=["indexing", "multimodal", "ingest"],
            supported_modalities=["pdf", "table", "image", "document"],
            safety_tags=["write", "compute"],
            route_hints=["tool", "indexing"],
            safe_for_auto_route=False,
            schema_identity="local.tools/index_multimodal_file",
            runtime_visibility="agent_internal",
            prompt_exposure_policy="hidden",
            resource_exposure_policy="handle_only",
            is_read_only=False,
            is_destructive=False,
            is_concurrency_safe=False,
        ),
        ToolDefinition(
            name="list_dir",
            display_name="列出目录",
            operation_id="op.list_dir",
            module="tools.file_system_tools",
            factory=lambda base_dir: ListDirTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "directory", "workspace", "path"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "directory_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/list_dir",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="stat_path",
            display_name="查看路径信息",
            operation_id="op.stat_path",
            module="tools.file_system_tools",
            factory=lambda base_dir: StatPathTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "metadata"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "path_metadata"],
            safe_for_auto_route=False,
            schema_identity="local.tools/stat_path",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="path_exists",
            display_name="检查路径是否存在",
            operation_id="op.path_exists",
            module="tools.file_system_tools",
            factory=lambda base_dir: PathExistsTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "existence"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "path_check"],
            safe_for_auto_route=False,
            schema_identity="local.tools/path_exists",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="glob_paths",
            display_name="按通配符查找路径",
            operation_id="op.glob_paths",
            module="tools.file_system_tools",
            factory=lambda base_dir: GlobPathsTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["pattern"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "path", "workspace", "glob"],
            supported_modalities=["workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_path_search", "glob_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/glob_paths",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="search_files",
            display_name="搜索文件",
            operation_id="op.search_files",
            module="tools.search_files_tool",
            factory=lambda base_dir: SearchFilesTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "search", "path", "workspace", "workspace_path_search"],
            supported_modalities=["text", "code", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_path_search", "file_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/search_files",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="search_text",
            display_name="搜索文本",
            operation_id="op.search_text",
            module="tools.search_files_tool",
            factory=lambda base_dir: SearchTextTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["query"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "search", "text_search", "workspace", "code_search"],
            supported_modalities=["text", "code", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_text_search", "text_search", "code_search"],
            safe_for_auto_route=True,
            schema_identity="local.tools/search_text",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="read_file",
            display_name="读取文件",
            operation_id="op.read_file",
            module="tools.read_file_tool",
            factory=lambda base_dir: ReadFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(
                path_field="path",
                path_kind="workspace",
            ),
            output_contract=ToolOutputContract(display_mode="verbatim_text"),
            capability_tags=["file", "read", "local"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/read_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="read_structured_file",
            display_name="读取结构化文件",
            operation_id="op.read_structured_file",
            module="tools.structured_file_tool",
            factory=lambda base_dir: ReadStructuredFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path"],
                owner_scope="explicit_path",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            resolution_contract=ToolResolutionContract(path_field="path", path_kind="workspace"),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["file", "read", "structured_config", "workspace"],
            supported_modalities=["text", "document", "workspace"],
            safety_tags=["read"],
            route_hints=["tool", "workspace_read", "structured_config"],
            safe_for_auto_route=False,
            schema_identity="local.tools/read_structured_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="fetch_url",
            display_name="抓取网页",
            operation_id="op.fetch_url",
            module="tools.fetch_url_tool",
            factory=lambda _base_dir: FetchURLTool(),
            contract=ToolExecutionContract(
                required_inputs=["url"],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["web", "fetch", "verification"],
            supported_modalities=["web"],
            safety_tags=["read", "network"],
            route_hints=["tool", "verification"],
            safe_for_auto_route=False,
            schema_identity="local.tools/fetch_url",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="git_status",
            display_name="查看 Git 状态",
            operation_id="op.git_status",
            module="tools.git_tools",
            factory=lambda base_dir: GitStatusTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "status", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_status",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="git_diff",
            display_name="查看 Git 差异",
            operation_id="op.git_diff",
            module="tools.git_tools",
            factory=lambda base_dir: GitDiffTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "diff", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_diff",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="git_log",
            display_name="查看 Git 日志",
            operation_id="op.git_log",
            module="tools.git_tools",
            factory=lambda base_dir: GitLogTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "log", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_log",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="git_show",
            display_name="查看 Git 对象",
            operation_id="op.git_show",
            module="tools.git_tools",
            factory=lambda base_dir: GitShowTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=[],
                owner_scope="none",
                missing_binding_behavior="clarify",
                context_policy="inline",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["git", "show", "workspace", "vcs"],
            supported_modalities=["workspace", "system"],
            safety_tags=["read"],
            route_hints=["tool", "git_read"],
            safe_for_auto_route=False,
            schema_identity="local.tools/git_show",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=True,
        ),
        ToolDefinition(
            name="write_file",
            display_name="写入文件",
            operation_id="op.write_file",
            module="tools.write_file_tool",
            factory=lambda base_dir: WriteFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path", "content"],
                owner_scope="explicit_path",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_if_canonical"),
            capability_tags=["file", "write", "workspace"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["write", "local_write"],
            route_hints=["tool", "workspace_write"],
            safe_for_auto_route=False,
            schema_identity="local.tools/write_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=False,
            is_destructive=False,
            is_concurrency_safe=False,
        ),
        ToolDefinition(
            name="edit_file",
            display_name="编辑文件",
            operation_id="op.edit_file",
            module="tools.write_file_tool",
            factory=lambda base_dir: EditFileTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["path", "old_text", "new_text"],
                owner_scope="explicit_path",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text", persistence_policy="persist_if_canonical"),
            capability_tags=["file", "edit", "workspace"],
            supported_modalities=["text", "code", "document"],
            safety_tags=["write", "local_write"],
            route_hints=["tool", "workspace_edit"],
            safe_for_auto_route=False,
            schema_identity="local.tools/edit_file",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="explicit_resource",
            is_read_only=False,
            is_destructive=False,
            is_concurrency_safe=False,
        ),
        ToolDefinition(
            name="delegate_to_agent",
            display_name="委派子Agent",
            operation_id="op.delegate_to_agent",
            module="tools.delegate_to_agent_tool",
            factory=lambda _base_dir: DelegateToAgentTool(),
            contract=ToolExecutionContract(
                required_inputs=["instruction"],
                owner_scope="none",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="canonical",
            ),
            output_contract=ToolOutputContract(display_mode="summary_text"),
            capability_tags=["delegation", "agent", "orchestration"],
            supported_modalities=["text", "workspace"],
            safety_tags=["agent_execution"],
            route_hints=["tool", "delegation"],
            safe_for_auto_route=False,
            schema_identity="local.tools/delegate_to_agent",
            prompt_exposure_policy="schema_only",
            resource_exposure_policy="none",
            is_read_only=True,
            is_destructive=False,
            is_concurrency_safe=False,
        ),
        ToolDefinition(
            name="terminal",
            display_name="终端命令",
            operation_id="op.shell",
            module="tools.terminal_tool",
            factory=lambda base_dir: TerminalTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["command"],
                owner_scope="none",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="tool_raw",
            ),
            output_contract=ToolOutputContract(display_mode="raw_debug_only", persistence_policy="do_not_persist"),
            capability_tags=["shell", "terminal", "command"],
            supported_modalities=["system"],
            safety_tags=["write", "shell", "destructive"],
            route_hints=["tool", "local_command"],
            safe_for_auto_route=False,
            schema_identity="local.tools/terminal",
            runtime_visibility="agent_internal",
            prompt_exposure_policy="hidden",
            resource_exposure_policy="none",
            is_read_only=False,
            is_destructive=True,
            is_concurrency_safe=False,
        ),
        ToolDefinition(
            name="python_repl",
            display_name="Python 执行",
            operation_id="op.python_repl",
            module="tools.python_repl_tool",
            factory=lambda base_dir: PythonReplTool(root_dir=base_dir),
            contract=ToolExecutionContract(
                required_inputs=["code"],
                owner_scope="none",
                missing_binding_behavior="deny",
                context_policy="isolated",
                result_channel="tool_raw",
            ),
            output_contract=ToolOutputContract(display_mode="raw_debug_only", persistence_policy="do_not_persist"),
            capability_tags=["python", "repl", "scripting"],
            supported_modalities=["system"],
            safety_tags=["write", "compute", "shell"],
            route_hints=["tool", "local_scripting"],
            safe_for_auto_route=False,
            schema_identity="local.tools/python_repl",
            runtime_visibility="agent_internal",
            prompt_exposure_policy="hidden",
            resource_exposure_policy="none",
            is_read_only=False,
            is_destructive=False,
            is_concurrency_safe=False,
        ),
    ]


def get_tool_definitions() -> list[ToolDefinition]:
    return list(_tool_definitions())


def get_tool_definition_map() -> dict[str, ToolDefinition]:
    return {definition.name: definition for definition in get_tool_definitions()}


def build_tool_instances(base_dir: Path) -> list[BaseTool]:
    return [definition.build(base_dir) for definition in get_tool_definitions()]


def build_tool_registry_payload() -> dict[str, Any]:
    definitions = get_tool_definitions()
    return {
        "version": 2,
        "tool_count": len(definitions),
        "tools": [definition.to_registry_record() for definition in definitions],
    }
